### ISSUE TITLE
BQ Query Error: Data_Release column not in isb-cgc-bq.HTAN.clinical_tier1_demographics_current

### ISSUE THREAD

**Issue by vthorsson** [ncihtan/Community-Notebooks#7]
In 
[Explore_HTAN_Clinical_Biospecimen_Assay_Metadata.ipynb](https://github.com/ncihtan/Community-Notebooks/blob/master/HTAN/Python%20Notebooks/Explore_HTAN_Clinical_Biospecimen_Assay_Metadata.ipynb)
Section 4.1 references a column `Data_Release` in table `isb-cgc-bq.HTAN.clinical_tier1_demographics_current` 
but that column is not in the table. (`Data_Release` not included in _r4, was there e.g. in _r2).

**Comment by clarisse-lau** [comment]
Also pertains to: https://github.com/ncihtan/Community-Notebooks/blob/master/HTAN/R%20Notebooks/Explore_HTAN_Clinical_Biospecimen_Assay_Metadata.Rmd
